### ISSUE TITLE
Black border on around window

### ISSUE THREAD

**Issue by bgcarlisle** [wolfv/uberwriter#10]
When I open UberWriter, there's a big black border around the window.

This border disappears if I switch to dark mode, then back again.

**Comment by Menci** [comment]
+1

**Comment by francesca-c** [comment]
I had this problem too, on Linux Mint and previously on Elementary OS. There are some potential hack fixes that helped me on this forum, until it can be properly fixed in the code:

https://bugs.launchpad.net/uberwriter/+bug/1394717

**Comment by somas95** [comment]
[Fixed](https://github.com/wolfv/uberwriter/commit/dad4da1678ebc1500667a504cc85b65c70de044c) by @wolfv
