### ISSUE TITLE
Big transparent hole 

### ISSUE THREAD

**Issue by supergeante** [wolfv/uberwriter#11]
Hi,

I was using uberwriter in linux mint cinnamon with much pleasure and it suddendly went wrong. The screen has now a big transparent hole surrounded by the rest of the software. I've updated to the beta release and it's still the same. 

![capture du 2015-12-09 08 45 54](https://cloud.githubusercontent.com/assets/16158327/11679435/5c53135c-9e51-11e5-88e3-08e26eb78521.png)

Any idea or help is welcome.

**Comment by jonalmeida** [comment]
See #3. Seems to be the same issue.

Active development on UberWriter has stopped, but I'm sure @wolfv would be happy to accept PR requests. :smile:

**Comment by jonalmeida** [comment]
Owh, looks like you already commented there!

**Comment by somas95** [comment]
#22 - fixed
