### ISSUE TITLE
Ubuntu Trusty, on every key press: "TypeError: Couldn't find conversion for foreign struct 'cairo.Context'"

### ISSUE THREAD

**Issue by bksunday** [wolfv/uberwriter#12]
Hi,

After install uberwriter through your apt repository, I kept having this error:
`TypeError: Couldn't find conversion for foreign struct 'cairo.Context'`

I tried to install a couple of different libraries so that this error would stop.

Installing this package fixed the problem:
`apt-get install python3-gi-cairo`

**Comment by jonalmeida** [comment]
@bksunday See this readme for a longer list of dependencies I found missing: https://github.com/jonalmeida/UberWriter/blob/master/README.md
