### ISSUE TITLE
Pasting text "- [ ] " for GFM

### ISSUE THREAD

**Issue by govvin** [wolfv/uberwriter#16]
Pasting text "- [ ] " for GFM results in the following:

Original text: "Prepare a tracing/tagging guide for the task", then paste "- [ ] " in the beginning of the line.
Resulting text: "- Prepare[ ]  a tracing/tagging guide for the task"
Expected text: "- [ ]  Prepare a tracing/tagging guide for the task"

Using version: Version: 14.09.08-publicubuntu3
Platform: Ubuntu 14.04.4 LTS

**Comment by somas95** [comment]
Can't reproduce
