### ISSUE TITLE
Running uberwriter with GTK_IM_MODULE=xim causes a giant transparent hole to appear

### ISSUE THREAD

**Issue by mcjohnalds** [wolfv/uberwriter#3]
Setting the environment variable GTK_IM_MODULE=xim before running uberwriter  <br/> (`GTK_IM_MODULE=xim ./bin/uberwriter`) causes uberwriter to look like this:

![Screenshot](https://cloud.githubusercontent.com/assets/4696749/5577080/50103a76-9055-11e4-8dcb-da0e54c6bb6c.png)

As you can see, github is open in the background and shouldn't be visible.

Setting GTK_IM_MODULE=xim is necessary for custom [compose key](https://help.ubuntu.com/community/ComposeKey) sequences.

To make the finding a little more system independent, I have also tried this from a guest account with the same result.

I'll have a look around the code at some point to see what is causing the issue.

_Edit:_ Using uim instead of xim "fixes" the bug. I installed uim with `sudo apt-get install uim` and added the following to my ~/.gnomerc.

```
GTK_IM_MODULE=uim ; export GTK_IM_MODULE
QT_IM_MODULE=uim ; export QT_IM_MODULE
uim-xim &
XMODIFIERS=@im=uim ; export XMODIFIERS
```

**Comment by srcshelton** [comment]
On Ubuntu 15.04, UberWriter also launches with a huge transparent hole by default, but unsetting GTK_IM_MODULE does appear to fix this.

Even there though, I notice that whilst the centre of the window is transparent the very corners which should be rounded are actually non-transparently masked and so have white corners.

**Comment by supergeante** [comment]
Hi. I'm experiencing the same problem (Linux Mint Cinnamon Rafaela) but i cannot find .gnomerc. to do the changes. Could you advise me how to do ? Thanks !
