### ISSUE TITLE
Error on installation due to a wired path

### ISSUE THREAD

**Issue by yoandyshyno** [wolfv/uberwriter#31]
I got an error while trying to install the app. There are some references in the file `uberwriter/plugins/bibtex/bibtex.py` to an absolute path : `/home/wolfv/.....` 

This interrupt the installation process.

**Comment by wolfv** [comment]
Even with the current master branch?

**Comment by yoandyshyno** [comment]
Yes, it happens in the current master Branch.

**Comment by somas95** [comment]
#32 should solve the issue for now
