### ISSUE TITLE
Wrong inline syntaxis preview for one character words

### ISSUE THREAD

**Issue by somas95** [wolfv/uberwriter#41]
Better seen with an example:
\*a\* should return \**a*\* but returns \*a\* 
\*\*a\*\* should return \*\***a**\*\* but returns \*\**a*\*\*
\*\*\*a\*\*\* should return \*\*\****a***\*\*\* but returns \*\*\***a**\*\*\*
Etc.

**Comment by wolfv** [comment]
this is fixed with your last changes, right? :)

**Comment by somas95** [comment]
Yes :)
Fixed with 72c568f0316ea8ac409983a0aa8587a638249303
