### ISSUE TITLE
Spellcheck isn't working properly

### ISSUE THREAD

**Issue by mdeboer** [wolfv/uberwriter#6]
The right-click menu shows two independent language sub-menus. After switching languages it seems that the old dictionary is never unloaded, text in both languages is marked as valid now.

**Comment by tomnatt** [comment]
I thought the spellcheck was not working, however it seems that it is the (formatting of the) highlighting that is failing. If I select all (ctrl+A) the underline indicator appears. Under normal viewing it is invisible.
