### ISSUE TITLE
Window shadow is borked

### ISSUE THREAD

**Issue by clauseggers** [wolfv/uberwriter#8]
![screen shot 2015-06-01 at 21 34 25](https://cloud.githubusercontent.com/assets/868987/7921552/865cbaea-08a6-11e5-9496-c94bdabdb9d5.png)

**Comment by clauseggers** [comment]
After rebooting this issue when away.

**Comment by wolfv** [comment]
Hi Claus, 

thanks for the bug report. I have noticed this issue, too, and I am quite sure that it is somewhere upstream in GTK or mutter. 

I didn't notice this problem anymore on more recent versions of Fedora like Fedora 22. 

What version of GTK are you on (or which distro/version?).

Nice theme by the way, I dig the blue header bar :)

Wolf

**Comment by clauseggers** [comment]
Hi Wolfgang
I’ve only tried it on OpenSuSE Tumbleweed so that might very well be the issue. After Gnome 3.16 Tumbleweed has been a little flakey. Keep up the good work! I have iA Writer on my Mac and really wanted a similar app on Gnome, and yours is the only one I can stand to look at.

NB: The theme is Paper <http://snwh.org/paper/> with a few tweaks of my own. You can see them in my dotfiles <https://github.com/clauseggers/dotfiles>
